# Generated by Django 3.2.9 on 2021-12-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='description',
            field=models.TextField(help_text='Enter a short description of the game', max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_review', models.TextField()),
                ('rating', models.CharField(choices=[('0', '0'), ('.5', '.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='0', max_length=3)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_club_app.boardgame')),
            ],
        ),
    ]
